# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59e099217bb898548e7fdd4eb1b2e362ffafc8d7bc9c9c9bd300fcd362d76294071b38bb8f615b5b5a7c7cee6b1cf51948615334260c19022bf8ffc816ca95ba

test:
  secret_key_base: c4e95a52789de6d823087d88fefcef4fff89171ab541091fecdcb6d419e79259c8d60ec80478878ae6b5dcfa34d9a4b78a329bf05ec9454a2656a055a786579c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
