# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

State.create(name: 'Alabama', abv: 'AL')
State.create(name: 'Alaska', abv: 'AK')
State.create(name: 'Arizona', abv: 'AZ')
State.create(name: 'Arkansas', abv: 'AR')
State.create(name: 'California', abv: 'CA')
State.create(name: 'Colorado', abv: 'CO')
State.create(name: 'Connecticut', abv: 'CT')
State.create(name: 'Delaware', abv: 'DE')
State.create(name: 'Florida', abv: 'FL')
State.create(name: 'Georgia', abv: 'GA')
State.create(name: 'Hawaii', abv: 'HI')
State.create(name: 'Idaho', abv: 'ID')
State.create(name: 'Illinois', abv: 'IL')
State.create(name: 'Indiana', abv: 'IN')
State.create(name: 'Iowa', abv: 'IA')
State.create(name: 'Kansas', abv: 'KS')
State.create(name: 'Kentucky', abv: 'KY')
State.create(name: 'Louisiana', abv: 'LA')
State.create(name: 'Maine', abv: 'ME')
State.create(name: 'Maryland', abv: 'MD')
State.create(name: 'Massachusetts', abv: 'MA')
State.create(name: 'Michigan', abv: 'MI')
State.create(name: 'Minnesota', abv: 'MN')
State.create(name: 'Mississippi', abv: 'MS')
State.create(name: 'Missouri', abv: 'MO')
State.create(name: 'Montana', abv: 'MT')
State.create(name: 'Nebraska', abv: 'NE')
State.create(name: 'Nevada', abv: 'NV')
State.create(name: 'New Hampshire', abv: 'NH')
State.create(name: 'New Jersey', abv: 'NJ')
State.create(name: 'New Mexico', abv: 'NM')
State.create(name: 'New York', abv: 'NY')
State.create(name: 'North Carolina', abv: 'NC')
State.create(name: 'North Dakota', abv: 'ND')
State.create(name: 'Ohio', abv: 'OH')
State.create(name: 'Oklahoma', abv: 'OK')
State.create(name: 'Oregon', abv: 'OR')
State.create(name: 'Pennsylvania', abv: 'PA')
State.create(name: 'Rhode Island', abv: 'RI')
State.create(name: 'South Carolina', abv: 'SC')
State.create(name: 'South Dakota', abv: 'SD')
State.create(name: 'Tennessee', abv: 'TN')
State.create(name: 'Texas', abv: 'TX')
State.create(name: 'Utah', abv: 'UT')
State.create(name: 'Vermont', abv: 'VT')
State.create(name: 'Virginia', abv: 'VA')
State.create(name: 'Washington', abv: 'WA')
State.create(name: 'West Virginia', abv: 'WV')
State.create(name: 'Wisconsin', abv: 'WI')
State.create(name: 'Wyoming', abv: 'WY')