# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b8be51d637d500092910ec385afc03ded02497069f1341f83ee5e07a4a1347056617bf93f75d4884e758f8afe821679dcd755f9a5cd3147315e03c55a97b585

test:
  secret_key_base: da5e70339226371bca4a1c707043437f3b3f6f8e9fde53635b8223ddf5ceae1d353711f47b1f45e130fb859b5212efe1b38fe3f4c4200bf5075979219c1f810d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
