development:
  adapter: postgresql
  encoding: utf8
  database: critters
  pool: 5
  username: localflavor
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: critters
  pool: 5
  username: localflavor
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: critters
  pool: 5
  username: localflavor
  password: